.PHONY:

OBJECTS = \

TEST_OBJECTS = \
          gtest/src/gtest-death-test.o \
          gtest/src/gtest-filepath.o \
          gtest/src/gtest-port.o \
          gtest/src/gtest-printers.o \
          gtest/src/gtest-test-part.o \
          gtest/src/gtest-typed-test.o \
          gtest/src/gtest.o \
          gmock/src/gmock-cardinalities.o \
          gmock/src/gmock-internal-utils.o \
          gmock/src/gmock-matchers.o \
          gmock/src/gmock-spec-builders.o \
          gmock/src/gmock.o \

PROJECT_ROOT = ..
LIBRARY_NAME = testing

include $(PROJECT_ROOT)/common.mk
include $(PROJECT_ROOT)/library.mk
