.PHONY:

OBJECTS = \
          proxy/callback_tracker.o \
          proxy/dispatcher.o \
          proxy/host_dispatcher.o \
          proxy/host_var_serialization_rules.o \
          proxy/interface_proxy.o \
          proxy/plugin_dispatcher.o \
          proxy/plugin_resource.o \
          proxy/plugin_resource_tracker.o \
          proxy/plugin_var_serialization_rules.o \
          proxy/plugin_var_tracker.o \
          proxy/ppapi_messages.o \
          proxy/ppapi_param_traits.o \
          proxy/ppb_buffer_proxy.o \
          proxy/ppb_char_set_proxy.o \
          proxy/ppb_core_proxy.o \
          proxy/ppb_cursor_control_proxy.o \
          proxy/ppb_flash_proxy.o \
          proxy/ppb_font_proxy.o \
          proxy/ppb_fullscreen_proxy.o \
          proxy/ppb_graphics_2d_proxy.o \
          proxy/ppb_image_data_proxy.o \
          proxy/ppb_instance_proxy.o \
          proxy/ppb_pdf_proxy.o \
          proxy/ppb_testing_proxy.o \
          proxy/ppb_url_loader_proxy.o \
          proxy/ppb_url_request_info_proxy.o \
          proxy/ppb_url_response_info_proxy.o \
          proxy/ppb_var_deprecated_proxy.o \
          proxy/ppp_class_proxy.o \
          proxy/ppp_instance_proxy.o \
          proxy/serialized_structs.o \
          proxy/serialized_var.o \

TEST_OBJECTS = \

PROJECT_ROOT = ..
LIBRARY_NAME = ppapi

include $(PROJECT_ROOT)/common.mk
include $(PROJECT_ROOT)/library.mk
